# Generated by Django 6.0 on 2025-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_created_at_alter_comment_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='metadata',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
    ]
