# Generated by Django 6.0 on 2025-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_metadata_alter_post_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
